/**
 * IR 샘플 데이터 시드 스크립트 (Part 1: 크리에이터 정의)
 * 
 * 100명 크리에이터 + 200개 모먼트
 * 모두 is_mock=true → 나중에 한방 삭제 가능
 * 
 * 실행: npx tsx scripts/seed-ir-data.ts
 * 삭제: npx tsx scripts/seed-ir-data.ts --delete
 */

import { createClient } from '@supabase/supabase-js'
import { config } from 'dotenv'
import { resolve } from 'path'

// Load .env.local
config({ path: resolve(__dirname, '..', '.env.local') })

// ============================================================
// Supabase 연결 (service role key for bypassing RLS)
// ============================================================
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!
if (!supabaseUrl || !supabaseKey) {
    console.error('❌ NEXT_PUBLIC_SUPABASE_URL 또는 SUPABASE_SERVICE_ROLE_KEY 환경변수가 없습니다')
    process.exit(1)
}
const supabase = createClient(supabaseUrl, supabaseKey)

// ============================================================
// 100명 크리에이터 데이터
// ============================================================
interface CreatorDef {
    display_name: string
    instagram_handle: string
    description: string
    primary_region: string
    tags: string[]
    followers_count: number
    price_video: number
    price_feed: number
    price_story: number
    channels: { platform: string; handle: string; followers_count: number; is_primary: boolean }[]
}

const CREATORS: CreatorDef[] = [
    // ── 뷰티 (10명) ──
    { display_name: "이하은", instagram_handle: "haeun.beauty", description: "뷰티/스킨케어 전문 크리에이터. 진솔한 리뷰와 성분 분석으로 소통합니다 💄", primary_region: "서울", tags: ["💄 뷰티"], followers_count: 34200, price_video: 400000, price_feed: 250000, price_story: 80000, channels: [{ platform: "instagram", handle: "@haeun.beauty", followers_count: 34200, is_primary: true }] },
    { display_name: "김서연", instagram_handle: "seo.yeon_skin", description: "민감성 피부 전문가. 성분 하나하나 꼼꼼히 따져보는 스킨케어 덕후예요", primary_region: "경기", tags: ["💄 뷰티", "💊 건강"], followers_count: 18500, price_video: 250000, price_feed: 150000, price_story: 50000, channels: [{ platform: "instagram", handle: "@seo.yeon_skin", followers_count: 18500, is_primary: true }] },
    { display_name: "윤채린", instagram_handle: "chaerin_glow", description: "글로우 메이크업 전문. 웨딩/촬영 메이크업도 해요 ✨", primary_region: "서울", tags: ["💄 뷰티", "💍 웨딩/결혼"], followers_count: 45800, price_video: 500000, price_feed: 300000, price_story: 100000, channels: [{ platform: "instagram", handle: "@chaerin_glow", followers_count: 45800, is_primary: true }, { platform: "youtube", handle: "채린뷰티", followers_count: 12300, is_primary: false }] },
    { display_name: "배수아", instagram_handle: "sua_cosmetics", description: "드럭스토어 화장품 위주 리뷰. 가성비 좋은 것만 골라드려요", primary_region: "인천", tags: ["💄 뷰티"], followers_count: 12400, price_video: 180000, price_feed: 100000, price_story: 40000, channels: [{ platform: "instagram", handle: "@sua_cosmetics", followers_count: 12400, is_primary: true }] },
    { display_name: "정유나", instagram_handle: "yuna_makeup", description: "데일리 메이크업 튜토리얼 전문. 초보자도 쉽게 따라할 수 있어요", primary_region: "서울", tags: ["💄 뷰티"], followers_count: 67300, price_video: 700000, price_feed: 400000, price_story: 150000, channels: [{ platform: "instagram", handle: "@yuna_makeup", followers_count: 67300, is_primary: true }, { platform: "youtube", handle: "유나메이크업", followers_count: 31200, is_primary: false }] },
    { display_name: "한예진", instagram_handle: "yejin_nails", description: "네일아트 & 셀프네일 크리에이터. 계절별 트렌드 네일 소개 💅", primary_region: "부산", tags: ["💄 뷰티", "🎨 취미/DIY"], followers_count: 21700, price_video: 280000, price_feed: 170000, price_story: 60000, channels: [{ platform: "instagram", handle: "@yejin_nails", followers_count: 21700, is_primary: true }] },
    { display_name: "조민경", instagram_handle: "mk_haircare", description: "헤어케어 전문. 탈모 고민부터 염색 관리까지 다뤄요", primary_region: "대구", tags: ["💄 뷰티"], followers_count: 15900, price_video: 220000, price_feed: 130000, price_story: 45000, channels: [{ platform: "instagram", handle: "@mk_haircare", followers_count: 15900, is_primary: true }] },
    { display_name: "황서현", instagram_handle: "seohyun_parfum", description: "향수 리뷰어. 200개 넘는 향수를 직접 테스트하고 기록합니다", primary_region: "서울", tags: ["💄 뷰티"], followers_count: 28300, price_video: 350000, price_feed: 200000, price_story: 70000, channels: [{ platform: "instagram", handle: "@seohyun_parfum", followers_count: 28300, is_primary: true }, { platform: "blog", handle: "향수일기", followers_count: 8400, is_primary: false }] },
    { display_name: "안소미", instagram_handle: "somi_skinlab", description: "피부과 전문의 출신 뷰티 크리에이터. 과학적 근거로 리뷰합니다", primary_region: "서울", tags: ["💄 뷰티", "💉 시술/병원"], followers_count: 89200, price_video: 900000, price_feed: 550000, price_story: 200000, channels: [{ platform: "instagram", handle: "@somi_skinlab", followers_count: 89200, is_primary: true }, { platform: "youtube", handle: "소미스킨", followers_count: 45600, is_primary: false }] },
    { display_name: "노예림", instagram_handle: "yerim_organic", description: "비건/클린뷰티 전문. 동물실험 안 하는 브랜드만 소개해요 🌿", primary_region: "제주", tags: ["💄 뷰티", "💊 건강"], followers_count: 11200, price_video: 180000, price_feed: 100000, price_story: 35000, channels: [{ platform: "instagram", handle: "@yerim_organic", followers_count: 11200, is_primary: true }] },

    // ── 패션 (10명) ──
    { display_name: "박지민", instagram_handle: "jimin_style", description: "오피스룩 & 데일리 코디 전문. 깔끔한 스타일링 좋아해요", primary_region: "서울", tags: ["👗 패션"], followers_count: 62800, price_video: 600000, price_feed: 350000, price_story: 120000, channels: [{ platform: "instagram", handle: "@jimin_style", followers_count: 62800, is_primary: true }] },
    { display_name: "최수빈", instagram_handle: "subin_ootd", description: "부산 기반 패션 크리에이터. 키 작은 체형 커버 코디 전문이에요", primary_region: "부산", tags: ["👗 패션"], followers_count: 22100, price_video: 300000, price_feed: 180000, price_story: 60000, channels: [{ platform: "instagram", handle: "@subin_ootd", followers_count: 22100, is_primary: true }] },
    { display_name: "김태희", instagram_handle: "taehee_closet", description: "미니멀 패션 & 캡슐 워드로브. 적게 입고 잘 입는 방법 공유", primary_region: "서울", tags: ["👗 패션", "🏡 리빙/인테리어"], followers_count: 38900, price_video: 450000, price_feed: 280000, price_story: 90000, channels: [{ platform: "instagram", handle: "@taehee_closet", followers_count: 38900, is_primary: true }, { platform: "blog", handle: "태희의옷장", followers_count: 15200, is_primary: false }] },
    { display_name: "이도윤", instagram_handle: "doyun_mens", description: "남성 패션 크리에이터. 직장인 캐주얼부터 스트릿까지", primary_region: "서울", tags: ["👗 패션"], followers_count: 31500, price_video: 380000, price_feed: 230000, price_story: 70000, channels: [{ platform: "instagram", handle: "@doyun_mens", followers_count: 31500, is_primary: true }] },
    { display_name: "강하린", instagram_handle: "harin_vintage", description: "빈티지/세컨핸드 패션 전문. 구제 쇼핑 투어 콘텐츠 제작", primary_region: "서울", tags: ["👗 패션", "✈️ 여행"], followers_count: 19800, price_video: 260000, price_feed: 160000, price_story: 55000, channels: [{ platform: "instagram", handle: "@harin_vintage", followers_count: 19800, is_primary: true }] },
    { display_name: "유지아", instagram_handle: "jia_luxury", description: "하이엔드 패션 & 명품 리뷰. 진품 감별 팁도 공유해요", primary_region: "서울", tags: ["👗 패션"], followers_count: 125000, price_video: 1500000, price_feed: 900000, price_story: 300000, channels: [{ platform: "instagram", handle: "@jia_luxury", followers_count: 125000, is_primary: true }, { platform: "youtube", handle: "지아럭셔리", followers_count: 52000, is_primary: false }] },
    { display_name: "오승아", instagram_handle: "seunga_sport", description: "스포츠웨어 & 애슬레저 전문. 운동하면서도 예쁘게 입어요", primary_region: "경기", tags: ["👗 패션", "🏋️ 헬스/운동"], followers_count: 27400, price_video: 330000, price_feed: 200000, price_story: 65000, channels: [{ platform: "instagram", handle: "@seunga_sport", followers_count: 27400, is_primary: true }] },
    { display_name: "전소이", instagram_handle: "soi_hanbok", description: "생활 한복 & 퓨전 한복 크리에이터. 전통미와 현대미의 조화", primary_region: "전주", tags: ["👗 패션", "🎬 영화/문화"], followers_count: 14700, price_video: 200000, price_feed: 120000, price_story: 40000, channels: [{ platform: "instagram", handle: "@soi_hanbok", followers_count: 14700, is_primary: true }] },
    { display_name: "임하늘", instagram_handle: "haneul_knit", description: "뜨개질 & 핸드메이드 패션. 직접 만들어 입는 삶을 공유해요 🧶", primary_region: "강원", tags: ["👗 패션", "🎨 취미/DIY"], followers_count: 9800, price_video: 150000, price_feed: 90000, price_story: 30000, channels: [{ platform: "instagram", handle: "@haneul_knit", followers_count: 9800, is_primary: true }] },
    { display_name: "심나래", instagram_handle: "narae_plus", description: "플러스사이즈 패션 크리에이터. 모든 체형이 아름답습니다 🦋", primary_region: "서울", tags: ["👗 패션"], followers_count: 43200, price_video: 500000, price_feed: 300000, price_story: 100000, channels: [{ platform: "instagram", handle: "@narae_plus", followers_count: 43200, is_primary: true }, { platform: "youtube", handle: "나래플러스", followers_count: 18500, is_primary: false }] },

    // ── 맛집/푸드 (10명) ──
    { display_name: "오민지", instagram_handle: "minji_eats", description: "서울 맛집 전문 리뷰어. 매주 새로운 맛집을 찾아다닙니다 🍽️", primary_region: "서울", tags: ["🍽️ 맛집"], followers_count: 87200, price_video: 800000, price_feed: 500000, price_story: 180000, channels: [{ platform: "instagram", handle: "@minji_eats", followers_count: 87200, is_primary: true }] },
    { display_name: "장예린", instagram_handle: "yerin_food", description: "대구 맛집 & 홈쿠킹 크리에이터. 집밥 같은 편안한 콘텐츠", primary_region: "대구", tags: ["🍽️ 맛집"], followers_count: 28900, price_video: 350000, price_feed: 200000, price_story: 70000, channels: [{ platform: "instagram", handle: "@yerin_food", followers_count: 28900, is_primary: true }] },
    { display_name: "강호진", instagram_handle: "hojin_chef", description: "전직 호텔 셰프. 프로의 시선으로 음식을 리뷰합니다", primary_region: "서울", tags: ["🍽️ 맛집"], followers_count: 56300, price_video: 600000, price_feed: 380000, price_story: 130000, channels: [{ platform: "instagram", handle: "@hojin_chef", followers_count: 56300, is_primary: true }, { platform: "youtube", handle: "호진셰프", followers_count: 24500, is_primary: false }] },
    { display_name: "박소담", instagram_handle: "sodam_baking", description: "홈베이킹 & 디저트 레시피 전문. 달콤한 콘텐츠 만들어요 🍰", primary_region: "경기", tags: ["🍽️ 맛집", "🎨 취미/DIY"], followers_count: 33100, price_video: 400000, price_feed: 240000, price_story: 80000, channels: [{ platform: "instagram", handle: "@sodam_baking", followers_count: 33100, is_primary: true }] },
    { display_name: "정우성", instagram_handle: "ws_gourmet", description: "파인다이닝 & 와인 전문 리뷰어. 격식있는 미식 탐험", primary_region: "서울", tags: ["🍽️ 맛집"], followers_count: 41700, price_video: 480000, price_feed: 300000, price_story: 100000, channels: [{ platform: "instagram", handle: "@ws_gourmet", followers_count: 41700, is_primary: true }] },
    { display_name: "이수진", instagram_handle: "sujin_vegan", description: "비건 식당 & 식물성 음식 전문. 지구를 위한 맛있는 선택 🌱", primary_region: "서울", tags: ["🍽️ 맛집", "💊 건강"], followers_count: 16800, price_video: 230000, price_feed: 140000, price_story: 50000, channels: [{ platform: "instagram", handle: "@sujin_vegan", followers_count: 16800, is_primary: true }] },
    { display_name: "김태영", instagram_handle: "taeyoung_street", description: "길거리 음식 & B급 맛집 전문. 화려하진 않지만 맛은 최고", primary_region: "부산", tags: ["🍽️ 맛집", "✈️ 여행"], followers_count: 72400, price_video: 750000, price_feed: 450000, price_story: 160000, channels: [{ platform: "instagram", handle: "@taeyoung_street", followers_count: 72400, is_primary: true }, { platform: "youtube", handle: "태영스트릿", followers_count: 38900, is_primary: false }] },
    { display_name: "문가영", instagram_handle: "gayoung_cafe", description: "카페 투어 전문. 서울/경기 신상 카페 매주 소개 ☕", primary_region: "서울", tags: ["🍽️ 맛집"], followers_count: 24600, price_video: 300000, price_feed: 180000, price_story: 60000, channels: [{ platform: "instagram", handle: "@gayoung_cafe", followers_count: 24600, is_primary: true }] },
    { display_name: "한지호", instagram_handle: "jiho_ramen", description: "라면 덕후. 전국 라면 맛집과 편의점 신상 라면 리뷰 🍜", primary_region: "서울", tags: ["🍽️ 맛집"], followers_count: 19300, price_video: 260000, price_feed: 150000, price_story: 50000, channels: [{ platform: "instagram", handle: "@jiho_ramen", followers_count: 19300, is_primary: true }, { platform: "tiktok", handle: "@jiho_ramen", followers_count: 45200, is_primary: false }] },
    { display_name: "배은지", instagram_handle: "eunji_homecook", description: "자취생 요리 전문. 간단하고 맛있는 한 끼 레시피 공유", primary_region: "대전", tags: ["🍽️ 맛집"], followers_count: 13500, price_video: 190000, price_feed: 110000, price_story: 40000, channels: [{ platform: "instagram", handle: "@eunji_homecook", followers_count: 13500, is_primary: true }] },

    // ── 여행 (8명) ──
    { display_name: "류하영", instagram_handle: "hayoung_trip", description: "해외여행 전문 크리에이터. 30개국 이상 여행 경험. 가성비 여행 전문 ✈️", primary_region: "전국", tags: ["✈️ 여행"], followers_count: 104500, price_video: 1200000, price_feed: 700000, price_story: 250000, channels: [{ platform: "instagram", handle: "@hayoung_trip", followers_count: 104500, is_primary: true }, { platform: "youtube", handle: "하영트립", followers_count: 58000, is_primary: false }] },
    { display_name: "윤지우", instagram_handle: "jiwoo.traveler", description: "국내 여행 전문. 숨겨진 로컬 명소를 발굴합니다", primary_region: "서울", tags: ["✈️ 여행"], followers_count: 31400, price_video: 380000, price_feed: 220000, price_story: 75000, channels: [{ platform: "instagram", handle: "@jiwoo.traveler", followers_count: 31400, is_primary: true }] },
    { display_name: "차준호", instagram_handle: "junho_camping", description: "캠핑 & 차박 전문. 장비 리뷰부터 캠핑 요리까지 ⛺", primary_region: "경기", tags: ["✈️ 여행", "🍽️ 맛집"], followers_count: 47800, price_video: 550000, price_feed: 320000, price_story: 110000, channels: [{ platform: "instagram", handle: "@junho_camping", followers_count: 47800, is_primary: true }, { platform: "youtube", handle: "준호캠핑", followers_count: 21300, is_primary: false }] },
    { display_name: "서유진", instagram_handle: "yujin_island", description: "제주도 로컬 가이드. 제주 토박이가 알려주는 진짜 제주 🌊", primary_region: "제주", tags: ["✈️ 여행"], followers_count: 36200, price_video: 420000, price_feed: 260000, price_story: 85000, channels: [{ platform: "instagram", handle: "@yujin_island", followers_count: 36200, is_primary: true }] },
    { display_name: "이현우", instagram_handle: "hyunwoo_photo", description: "여행 사진작가. 풍경 사진과 함께 여행 스토리를 전합니다 📸", primary_region: "서울", tags: ["✈️ 여행", "🎨 취미/DIY"], followers_count: 58900, price_video: 650000, price_feed: 400000, price_story: 140000, channels: [{ platform: "instagram", handle: "@hyunwoo_photo", followers_count: 58900, is_primary: true }] },
    { display_name: "박서율", instagram_handle: "seoyul_solo", description: "혼자 여행 전문. 솔로 트래블러를 위한 팁과 추천 코스", primary_region: "서울", tags: ["✈️ 여행"], followers_count: 23100, price_video: 290000, price_feed: 170000, price_story: 60000, channels: [{ platform: "instagram", handle: "@seoyul_solo", followers_count: 23100, is_primary: true }, { platform: "blog", handle: "서율의혼여행", followers_count: 9800, is_primary: false }] },
    { display_name: "김나윤", instagram_handle: "nayun_luxury_trip", description: "호캉스 & 럭셔리 여행 전문. 호텔/리조트 솔직 후기", primary_region: "서울", tags: ["✈️ 여행"], followers_count: 82300, price_video: 950000, price_feed: 580000, price_story: 200000, channels: [{ platform: "instagram", handle: "@nayun_luxury_trip", followers_count: 82300, is_primary: true }] },
    { display_name: "정재민", instagram_handle: "jaemin_drive", description: "드라이브 코스 전문. 전국 해안도로/산악도로 투어 🚗", primary_region: "전국", tags: ["✈️ 여행"], followers_count: 18700, price_video: 250000, price_feed: 150000, price_story: 50000, channels: [{ platform: "instagram", handle: "@jaemin_drive", followers_count: 18700, is_primary: true }, { platform: "youtube", handle: "재민드라이브", followers_count: 7200, is_primary: false }] },

    // ── 건강/다이어트/시술 (8명) ──
    { display_name: "정다현", instagram_handle: "dahyun.fit", description: "헬스/필라테스 트레이너 겸 크리에이터. 바디프로필 챌린지 진행 🔥", primary_region: "서울", tags: ["🏋️ 헬스/운동"], followers_count: 41500, price_video: 450000, price_feed: 280000, price_story: 90000, channels: [{ platform: "instagram", handle: "@dahyun.fit", followers_count: 41500, is_primary: true }] },
    { display_name: "한소율", instagram_handle: "soyul_diet", description: "다이어트 식단 & 운동 일지. -15kg 감량 경험 공유", primary_region: "인천", tags: ["🥗 다이어트", "💊 건강"], followers_count: 15300, price_video: 200000, price_feed: 120000, price_story: 40000, channels: [{ platform: "instagram", handle: "@soyul_diet", followers_count: 15300, is_primary: true }] },
    { display_name: "서윤아", instagram_handle: "yuna_health", description: "영양사 출신 건강 크리에이터. 과학적 근거 위주 건강 정보", primary_region: "서울", tags: ["💊 건강"], followers_count: 29700, price_video: 350000, price_feed: 200000, price_story: 70000, channels: [{ platform: "instagram", handle: "@yuna_health", followers_count: 29700, is_primary: true }, { platform: "blog", handle: "윤아헬스로그", followers_count: 11200, is_primary: false }] },
    { display_name: "문정아", instagram_handle: "jeonga_clinic", description: "피부과/성형외과 시술 솔직 후기. 가격/효과 투명하게 공개", primary_region: "서울", tags: ["💉 시술/병원", "💄 뷰티"], followers_count: 58400, price_video: 700000, price_feed: 400000, price_story: 150000, channels: [{ platform: "instagram", handle: "@jeonga_clinic", followers_count: 58400, is_primary: true }] },
    { display_name: "김동건", instagram_handle: "donggun_muscle", description: "보디빌딩 & 생활 체육 크리에이터. 벌크업/컷팅 노하우", primary_region: "부산", tags: ["🏋️ 헬스/운동"], followers_count: 73200, price_video: 800000, price_feed: 480000, price_story: 170000, channels: [{ platform: "instagram", handle: "@donggun_muscle", followers_count: 73200, is_primary: true }, { platform: "youtube", handle: "동건머슬", followers_count: 41000, is_primary: false }] },
    { display_name: "이시은", instagram_handle: "sieun_yoga", description: "요가 강사 겸 크리에이터. 마음 챙김 & 명상 콘텐츠도 함께 🧘", primary_region: "서울", tags: ["🏋️ 헬스/운동", "💊 건강"], followers_count: 26400, price_video: 320000, price_feed: 190000, price_story: 65000, channels: [{ platform: "instagram", handle: "@sieun_yoga", followers_count: 26400, is_primary: true }] },
    { display_name: "박채은", instagram_handle: "chaeun_detox", description: "해독 주스 & 디톡스 전문. 건강한 식습관 만들기 프로젝트", primary_region: "서울", tags: ["🥗 다이어트", "💊 건강"], followers_count: 14800, price_video: 200000, price_feed: 120000, price_story: 40000, channels: [{ platform: "instagram", handle: "@chaeun_detox", followers_count: 14800, is_primary: true }] },
    { display_name: "우지현", instagram_handle: "jihyun_derm", description: "피부과 레지던트 출신. 시술 전후 비교 & 관리법 공유", primary_region: "서울", tags: ["💉 시술/병원"], followers_count: 44100, price_video: 520000, price_feed: 320000, price_story: 110000, channels: [{ platform: "instagram", handle: "@jihyun_derm", followers_count: 44100, is_primary: true }, { platform: "youtube", handle: "지현피부과", followers_count: 19800, is_primary: false }] },

    // ── 리빙/인테리어/웨딩 (8명) ──
    { display_name: "송채원", instagram_handle: "chaewon_home", description: "셀프 인테리어 & 수납 정리 전문. 작은 공간도 넓게 쓰는 법", primary_region: "경기", tags: ["🏡 리빙/인테리어"], followers_count: 45600, price_video: 500000, price_feed: 300000, price_story: 100000, channels: [{ platform: "instagram", handle: "@chaewon_home", followers_count: 45600, is_primary: true }] },
    { display_name: "임서아", instagram_handle: "seoa_living", description: "미니멀 라이프 & 살림 크리에이터. 심플한 생활의 행복", primary_region: "서울", tags: ["🏡 리빙/인테리어"], followers_count: 19800, price_video: 250000, price_feed: 150000, price_story: 50000, channels: [{ platform: "instagram", handle: "@seoa_living", followers_count: 19800, is_primary: true }] },
    { display_name: "백하늘", instagram_handle: "haneul_wedding", description: "웨딩 플래너 출신 크리에이터. 결혼 준비 A to Z 가이드 💍", primary_region: "서울", tags: ["💍 웨딩/결혼"], followers_count: 26700, price_video: 350000, price_feed: 200000, price_story: 70000, channels: [{ platform: "instagram", handle: "@haneul_wedding", followers_count: 26700, is_primary: true }] },
    { display_name: "유라온", instagram_handle: "raon_newlywed", description: "신혼부부 살림 & 인테리어. 20평대 아파트 꾸미기 일기", primary_region: "경기", tags: ["🏡 리빙/인테리어", "💍 웨딩/결혼"], followers_count: 17300, price_video: 230000, price_feed: 140000, price_story: 45000, channels: [{ platform: "instagram", handle: "@raon_newlywed", followers_count: 17300, is_primary: true }] },
    { display_name: "김도경", instagram_handle: "dogyeong_plant", description: "플랜트 인테리어 전문. 반려 식물 100그루와 함께 사는 중 🌿", primary_region: "서울", tags: ["🏡 리빙/인테리어"], followers_count: 31200, price_video: 380000, price_feed: 230000, price_story: 75000, channels: [{ platform: "instagram", handle: "@dogyeong_plant", followers_count: 31200, is_primary: true }] },
    { display_name: "조은별", instagram_handle: "eunbyul_clean", description: "청소 & 정리정돈 전문. 묵은 때도 말끔히! 클리닝 팁 공유", primary_region: "서울", tags: ["🏡 리빙/인테리어"], followers_count: 22900, price_video: 290000, price_feed: 170000, price_story: 60000, channels: [{ platform: "instagram", handle: "@eunbyul_clean", followers_count: 22900, is_primary: true }, { platform: "youtube", handle: "은별클린", followers_count: 10200, is_primary: false }] },
    { display_name: "윤서진", instagram_handle: "seojin_kitchen", description: "주방 인테리어 & 주방용품 리뷰 전문. 요리하는 공간을 예쁘게", primary_region: "서울", tags: ["🏡 리빙/인테리어", "🍽️ 맛집"], followers_count: 15600, price_video: 210000, price_feed: 130000, price_story: 45000, channels: [{ platform: "instagram", handle: "@seojin_kitchen", followers_count: 15600, is_primary: true }] },
    { display_name: "하율아", instagram_handle: "yula_wedding_prep", description: "결혼 준비 브이로거. 스드메/예물/혼수 비용 투명 공개", primary_region: "서울", tags: ["💍 웨딩/결혼"], followers_count: 35400, price_video: 420000, price_feed: 250000, price_story: 85000, channels: [{ platform: "instagram", handle: "@yula_wedding_prep", followers_count: 35400, is_primary: true }, { platform: "youtube", handle: "하율웨딩", followers_count: 14300, is_primary: false }] },

    // ── 육아 (6명) ──
    { display_name: "구민서", instagram_handle: "minseo_baby", description: "3살 딸 키우는 육아 브이로거. 이유식부터 놀이까지", primary_region: "경기", tags: ["👶 육아"], followers_count: 53200, price_video: 550000, price_feed: 350000, price_story: 120000, channels: [{ platform: "instagram", handle: "@minseo_baby", followers_count: 53200, is_primary: true }, { platform: "youtube", handle: "민서맘", followers_count: 28000, is_primary: false }] },
    { display_name: "홍예은", instagram_handle: "yeeun_mom", description: "워킹맘 일상 & 육아 꿀팁. 일과 육아 양립 노하우 공유", primary_region: "서울", tags: ["👶 육아"], followers_count: 21400, price_video: 280000, price_feed: 170000, price_story: 55000, channels: [{ platform: "instagram", handle: "@yeeun_mom", followers_count: 21400, is_primary: true }] },
    { display_name: "손태양", instagram_handle: "taeyang_dad", description: "아빠 육아 크리에이터. 육아는 아빠도 함께! 👨‍👧 DAD 일기", primary_region: "서울", tags: ["👶 육아"], followers_count: 38700, price_video: 440000, price_feed: 270000, price_story: 90000, channels: [{ platform: "instagram", handle: "@taeyang_dad", followers_count: 38700, is_primary: true }, { platform: "youtube", handle: "태양아빠", followers_count: 15600, is_primary: false }] },
    { display_name: "최예나", instagram_handle: "yena_twins", description: "쌍둥이 육아 브이로거. 두 배의 사랑, 두 배의 소동 👶👶", primary_region: "인천", tags: ["👶 육아"], followers_count: 64200, price_video: 680000, price_feed: 420000, price_story: 150000, channels: [{ platform: "instagram", handle: "@yena_twins", followers_count: 64200, is_primary: true }, { platform: "youtube", handle: "예나쌍둥이", followers_count: 35200, is_primary: false }] },
    { display_name: "박나라", instagram_handle: "nara_montessori", description: "몬테소리 교육 & 집콕 놀이 전문. 아이 발달을 돕는 콘텐츠", primary_region: "서울", tags: ["👶 육아", "🎓 교육/강의"], followers_count: 27800, price_video: 340000, price_feed: 200000, price_story: 70000, channels: [{ platform: "instagram", handle: "@nara_montessori", followers_count: 27800, is_primary: true }] },
    { display_name: "이하율", instagram_handle: "hayul_pregmom", description: "임신/출산 정보 크리에이터. 산전 요가, 태교 음악까지 🤰", primary_region: "경기", tags: ["👶 육아", "💊 건강"], followers_count: 16900, price_video: 220000, price_feed: 130000, price_story: 45000, channels: [{ platform: "instagram", handle: "@hayul_pregmom", followers_count: 16900, is_primary: true }] },

    // ── 테크/게임 (8명) ──
    { display_name: "남도현", instagram_handle: "dohyun_tech", description: "IT 리뷰어. 스마트폰/노트북/가젯 심층 리뷰 전문 🔧", primary_region: "서울", tags: ["💻 테크/IT"], followers_count: 73800, price_video: 900000, price_feed: 500000, price_story: 180000, channels: [{ platform: "instagram", handle: "@dohyun_tech", followers_count: 73800, is_primary: true }, { platform: "youtube", handle: "도현테크", followers_count: 42000, is_primary: false }] },
    { display_name: "강지훈", instagram_handle: "jihoon_game", description: "게임 리뷰어 & 스트리머. 콘솔/PC 게임 다 다뤄요 🎮", primary_region: "경기", tags: ["🎮 게임", "💻 테크/IT"], followers_count: 48900, price_video: 550000, price_feed: 300000, price_story: 100000, channels: [{ platform: "instagram", handle: "@jihoon_game", followers_count: 48900, is_primary: true }, { platform: "youtube", handle: "지훈게이밍", followers_count: 67000, is_primary: false }] },
    { display_name: "위성민", instagram_handle: "sungmin_dev", description: "개발자 겸 테크 크리에이터. AI/코딩 입문 콘텐츠 제작", primary_region: "서울", tags: ["💻 테크/IT", "🎓 교육/강의"], followers_count: 34500, price_video: 400000, price_feed: 250000, price_story: 80000, channels: [{ platform: "instagram", handle: "@sungmin_dev", followers_count: 34500, is_primary: true }, { platform: "youtube", handle: "성민개발", followers_count: 18900, is_primary: false }] },
    { display_name: "류가은", instagram_handle: "gaeun_apple", description: "애플 생태계 전문. 아이폰/맥/아이패드 활용법 극대화 🍎", primary_region: "서울", tags: ["💻 테크/IT"], followers_count: 55600, price_video: 620000, price_feed: 380000, price_story: 130000, channels: [{ platform: "instagram", handle: "@gaeun_apple", followers_count: 55600, is_primary: true }] },
    { display_name: "조민규", instagram_handle: "mingyu_esport", description: "e스포츠 & 모바일 게임 전문. 대회 해설부터 공략까지", primary_region: "서울", tags: ["🎮 게임"], followers_count: 91300, price_video: 1000000, price_feed: 600000, price_story: 220000, channels: [{ platform: "instagram", handle: "@mingyu_esport", followers_count: 91300, is_primary: true }, { platform: "youtube", handle: "민규이스포츠", followers_count: 128000, is_primary: false }, { platform: "tiktok", handle: "@mingyu_esport", followers_count: 85000, is_primary: false }] },
    { display_name: "한다인", instagram_handle: "dain_gadget", description: "가전/스마트홈 리뷰어. 새로운 가젯 입양 일기 📱", primary_region: "서울", tags: ["💻 테크/IT", "🏡 리빙/인테리어"], followers_count: 27100, price_video: 330000, price_feed: 200000, price_story: 65000, channels: [{ platform: "instagram", handle: "@dain_gadget", followers_count: 27100, is_primary: true }] },
    { display_name: "신우재", instagram_handle: "woojae_audio", description: "오디오/음향 장비 전문 리뷰어. 이어폰부터 스피커까지 🎧", primary_region: "서울", tags: ["💻 테크/IT"], followers_count: 18200, price_video: 240000, price_feed: 140000, price_story: 50000, channels: [{ platform: "instagram", handle: "@woojae_audio", followers_count: 18200, is_primary: true }, { platform: "youtube", handle: "우재오디오", followers_count: 9400, is_primary: false }] },
    { display_name: "권하음", instagram_handle: "haeum_retro", description: "레트로 게임 & 닌텐도 전문. 옛날 게임의 감성을 전합니다", primary_region: "대전", tags: ["🎮 게임"], followers_count: 13600, price_video: 190000, price_feed: 110000, price_story: 40000, channels: [{ platform: "instagram", handle: "@haeum_retro", followers_count: 13600, is_primary: true }] },

    // ── 반려동물 (6명) ──
    { display_name: "허은채", instagram_handle: "eunchae_pet", description: "골든리트리버 '보리'와 함께하는 반려견 일상 크리에이터 🐕", primary_region: "서울", tags: ["🐶 반려동물"], followers_count: 39100, price_video: 400000, price_feed: 250000, price_story: 80000, channels: [{ platform: "instagram", handle: "@eunchae_pet", followers_count: 39100, is_primary: true }] },
    { display_name: "권나연", instagram_handle: "nayeon_puppy", description: "포메라니안 '꾸미' 집사. 소형견 케어 & 간식 리뷰", primary_region: "부산", tags: ["🐶 반려동물"], followers_count: 16200, price_video: 200000, price_feed: 120000, price_story: 40000, channels: [{ platform: "instagram", handle: "@nayeon_puppy", followers_count: 16200, is_primary: true }] },
    { display_name: "남시우", instagram_handle: "siwoo_cats", description: "고양이 3마리 집사. 다묘 가정의 일상 & 고양이 용품 리뷰 🐱", primary_region: "서울", tags: ["🐶 반려동물"], followers_count: 52800, price_video: 580000, price_feed: 350000, price_story: 120000, channels: [{ platform: "instagram", handle: "@siwoo_cats", followers_count: 52800, is_primary: true }, { platform: "youtube", handle: "시우네고양이", followers_count: 32400, is_primary: false }] },
    { display_name: "정아린", instagram_handle: "arin_petfood", description: "반려동물 영양사. 수제간식 레시피 & 사료 성분 분석 전문", primary_region: "경기", tags: ["🐶 반려동물", "💊 건강"], followers_count: 21500, price_video: 270000, price_feed: 160000, price_story: 55000, channels: [{ platform: "instagram", handle: "@arin_petfood", followers_count: 21500, is_primary: true }] },
    { display_name: "오태민", instagram_handle: "taemin_vet", description: "수의사 출신 크리에이터. 반려동물 건강 정보 & 응급처치 가이드", primary_region: "서울", tags: ["🐶 반려동물", "💊 건강"], followers_count: 67400, price_video: 750000, price_feed: 450000, price_story: 160000, channels: [{ platform: "instagram", handle: "@taemin_vet", followers_count: 67400, is_primary: true }, { platform: "youtube", handle: "태민수의사", followers_count: 38900, is_primary: false }] },
    { display_name: "백소리", instagram_handle: "sori_birdlife", description: "앵무새 & 이색 반려동물 크리에이터. 앵무새 '쏘리'와 함께 🦜", primary_region: "서울", tags: ["🐶 반려동물"], followers_count: 11800, price_video: 170000, price_feed: 100000, price_story: 35000, channels: [{ platform: "instagram", handle: "@sori_birdlife", followers_count: 11800, is_primary: true }, { platform: "tiktok", handle: "@sori_birdlife", followers_count: 28900, is_primary: false }] },

    // ── 도서/자기계발/교육 (6명) ──
    { display_name: "차은서", instagram_handle: "eunseo_book", description: "월 10권 이상 독서. 자기계발서 & 에세이 위주 리뷰 📚", primary_region: "대전", tags: ["📚 도서/자기계발"], followers_count: 12900, price_video: 180000, price_feed: 100000, price_story: 35000, channels: [{ platform: "instagram", handle: "@eunseo_book", followers_count: 12900, is_primary: true }] },
    { display_name: "양서준", instagram_handle: "seojun_film", description: "영화 평론가 겸 크리에이터. 독립영화부터 블록버스터까지 🎬", primary_region: "서울", tags: ["🎬 영화/문화"], followers_count: 33500, price_video: 400000, price_feed: 240000, price_story: 80000, channels: [{ platform: "instagram", handle: "@seojun_film", followers_count: 33500, is_primary: true }, { platform: "youtube", handle: "서준시네마", followers_count: 21800, is_primary: false }] },
    { display_name: "탁지윤", instagram_handle: "jiyun_money", description: "사회 초년생을 위한 재테크 크리에이터. 쉽게 설명하는 금융 💰", primary_region: "서울", tags: ["💰 재테크"], followers_count: 42300, price_video: 500000, price_feed: 300000, price_story: 100000, channels: [{ platform: "instagram", handle: "@jiyun_money", followers_count: 42300, is_primary: true }, { platform: "youtube", handle: "지윤재테크", followers_count: 28500, is_primary: false }] },
    { display_name: "고하진", instagram_handle: "hajin.craft", description: "핸드메이드 & 공예 크리에이터. 레진아트, 도자기, 캘리그라피 🎨", primary_region: "제주", tags: ["🎨 취미/DIY"], followers_count: 17600, price_video: 220000, price_feed: 130000, price_story: 45000, channels: [{ platform: "instagram", handle: "@hajin.craft", followers_count: 17600, is_primary: true }] },
    { display_name: "민서영", instagram_handle: "seoyoung_study", description: "공부법 & 자격증 크리에이터. 효율적인 학습법 공유 ✍️", primary_region: "서울", tags: ["🎓 교육/강의", "📚 도서/자기계발"], followers_count: 29100, price_video: 350000, price_feed: 210000, price_story: 70000, channels: [{ platform: "instagram", handle: "@seoyoung_study", followers_count: 29100, is_primary: true }, { platform: "youtube", handle: "서영공부법", followers_count: 16400, is_primary: false }] },
    { display_name: "한나리", instagram_handle: "nari_english", description: "영어 회화 전문 크리에이터. 원어민처럼 말하는 비법 공유 🇺🇸", primary_region: "서울", tags: ["🎓 교육/강의"], followers_count: 88500, price_video: 950000, price_feed: 560000, price_story: 200000, channels: [{ platform: "instagram", handle: "@nari_english", followers_count: 88500, is_primary: true }, { platform: "youtube", handle: "나리영어", followers_count: 125000, is_primary: false }, { platform: "tiktok", handle: "@nari_english", followers_count: 210000, is_primary: false }] },

    // ── 재테크/교육/기타 (6명) ──
    { display_name: "송준혁", instagram_handle: "junhyuk_invest", description: "주식 & 부동산 투자 크리에이터. 실전 투자 포트폴리오 공개", primary_region: "서울", tags: ["💰 재테크"], followers_count: 61200, price_video: 700000, price_feed: 420000, price_story: 150000, channels: [{ platform: "instagram", handle: "@junhyuk_invest", followers_count: 61200, is_primary: true }, { platform: "youtube", handle: "준혁투자", followers_count: 34500, is_primary: false }] },
    { display_name: "이수현", instagram_handle: "suhyun_crypto", description: "블록체인 & 가상자산 전문. 초보자도 이해할 수 있게 설명 ₿", primary_region: "서울", tags: ["💰 재테크", "💻 테크/IT"], followers_count: 37800, price_video: 450000, price_feed: 270000, price_story: 90000, channels: [{ platform: "instagram", handle: "@suhyun_crypto", followers_count: 37800, is_primary: true }] },
    { display_name: "진소라", instagram_handle: "sora_culture", description: "전시/공연 리뷰어. 미술관/갤러리 투어 크리에이터 🖼️", primary_region: "서울", tags: ["🎬 영화/문화", "✈️ 여행"], followers_count: 23400, price_video: 290000, price_feed: 180000, price_story: 60000, channels: [{ platform: "instagram", handle: "@sora_culture", followers_count: 23400, is_primary: true }] },
    { display_name: "김도하", instagram_handle: "doha_piano", description: "피아노 연주 크리에이터. K-POP 커버 & 힐링 연주 🎹", primary_region: "서울", tags: ["🎬 영화/문화", "🎨 취미/DIY"], followers_count: 46200, price_video: 520000, price_feed: 310000, price_story: 110000, channels: [{ platform: "instagram", handle: "@doha_piano", followers_count: 46200, is_primary: true }, { platform: "youtube", handle: "도하피아노", followers_count: 78000, is_primary: false }] },
    { display_name: "양해원", instagram_handle: "haewon_garden", description: "텃밭 & 가드닝 크리에이터. 베란다에서 키우는 채소 일기 🌱", primary_region: "경기", tags: ["🎨 취미/DIY", "🏡 리빙/인테리어"], followers_count: 14200, price_video: 190000, price_feed: 110000, price_story: 38000, channels: [{ platform: "instagram", handle: "@haewon_garden", followers_count: 14200, is_primary: true }] },
    { display_name: "정하은", instagram_handle: "haeun_calligraphy", description: "캘리그라피 작가 겸 크리에이터. 손글씨의 아름다움을 전합니다 ✒️", primary_region: "서울", tags: ["🎨 취미/DIY"], followers_count: 19500, price_video: 250000, price_feed: 150000, price_story: 50000, channels: [{ platform: "instagram", handle: "@haeun_calligraphy", followers_count: 19500, is_primary: true }, { platform: "blog", handle: "하은캘리", followers_count: 7800, is_primary: false }] },
]

// 여기까지가 Part 1입니다. Part 2 (모먼트 데이터 + 실행 로직)는 별도 파일에 작성합니다.
console.log(`✅ 크리에이터 ${CREATORS.length}명 정의 완료`)

export { CREATORS, supabase }
export type { CreatorDef }
