/**
 * seed-20-brands.ts
 * 
 * 20개의 현실적인 한국 브랜드 mock 계정을 Supabase에 생성합니다.
 * profiles 테이블의 role='brand'로 삽입하며,
 * 뷰티/패션/피트니스/라이프스타일 카테고리별로 균형 있게 구성합니다.
 */

import { createClient } from '@supabase/supabase-js'
import { config } from 'dotenv'
import { resolve } from 'path'

config({ path: resolve(__dirname, '..', '.env.local') })

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// ── 20개 브랜드 페르소나 정의
const BRANDS = [
    // ── 뷰티 (7)
    {
        email: 'marketing@amore-youthlab.kr',
        password: 'MockBrand2024!',
        display_name: '아모레 유스랩',
        bio: '젊은 세대를 위한 MZ 전용 더마코스메틱 브랜드. 피부과학 기반 스킨케어 라인.',
        avatar_url: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=200&h=200&fit=crop',
        website: 'https://www.amore-youthlab.kr',
        business_category: '뷰티/코스메틱',
        business_type: '주식회사',
        business_number: '101-81-23456',
        representative_name: '이재현',
        company_address: '서울특별시 용산구 한강대로 92, 아모레퍼시픽 R&D센터',
        company_phone: '02-6090-7000',
        contact_person_name: '김소연',
        contact_person_phone: '010-2341-5678',
        contact_person_email: 'soyeon.kim@amore-youthlab.kr',
        tax_email: 'tax@amore-youthlab.kr',
        tags: ['스킨케어', '더마코스메틱', '뷰티', 'MZ세대'],
        handle: 'amore_youthlab',
        instagram_handle: '@amore_youthlab',
        deposit_balance: 5000000,
    },
    {
        email: 'contact@innismekorea.com',
        password: 'MockBrand2024!',
        display_name: '이니스미 코리아',
        bio: '트렌디한 색조 메이크업 전문 브랜드. 퍼스널컬러 맞춤 립&아이 라인업.',
        avatar_url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=200&h=200&fit=crop',
        website: 'https://www.innismekorea.com',
        business_category: '뷰티/색조화장품',
        business_type: '주식회사',
        business_number: '211-86-45678',
        representative_name: '박민준',
        company_address: '서울특별시 강남구 영동대로 513, 코엑스타워 14F',
        company_phone: '02-3467-8900',
        contact_person_name: '정유진',
        contact_person_phone: '010-3456-7890',
        contact_person_email: 'yujin.jeong@innismekorea.com',
        tax_email: 'billing@innismekorea.com',
        tags: ['색조', '립스틱', '아이쉐도우', '퍼스널컬러'],
        handle: 'innisme_korea',
        instagram_handle: '@innisme_korea',
        deposit_balance: 3000000,
    },
    {
        email: 'brand@cellderma.co.kr',
        password: 'MockBrand2024!',
        display_name: '셀더마 스킨랩',
        bio: '피부과 전문의와 공동 개발한 기능성 스킨케어. 민감성 피부 특화 클리닉 라인.',
        avatar_url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=200&h=200&fit=crop',
        website: 'https://www.cellderma.co.kr',
        business_category: '뷰티/더마코스메틱',
        business_type: '주식회사',
        business_number: '314-81-89012',
        representative_name: '최현경',
        company_address: '경기도 수원시 영통구 삼성로 129, 셀더마 연구소',
        company_phone: '031-888-2200',
        contact_person_name: '한지수',
        contact_person_phone: '010-8890-1234',
        contact_person_email: 'jisoo.han@cellderma.co.kr',
        tax_email: 'account@cellderma.co.kr',
        tags: ['더마코스메틱', '민감성피부', '기능성', '피부과학'],
        handle: 'cellderma_skinlab',
        instagram_handle: '@cellderma_skinlab',
        deposit_balance: 4000000,
    },
    {
        email: 'hello@perfumehouse108.com',
        password: 'MockBrand2024!',
        display_name: '퍼퓸하우스 108',
        bio: '국내 독립 조향사가 만든 니치퍼퓸 브랜드. 한국 자연에서 영감받은 향수 컬렉션.',
        avatar_url: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=200&h=200&fit=crop',
        website: 'https://www.perfumehouse108.com',
        business_category: '뷰티/향수',
        business_type: '유한회사',
        business_number: '110-87-67890',
        representative_name: '윤서아',
        company_address: '서울특별시 성동구 성수이로 77, 성수동 스튜디오 2F',
        company_phone: '02-1234-5670',
        contact_person_name: '오민재',
        contact_person_phone: '010-5670-1234',
        contact_person_email: 'minjae.oh@perfumehouse108.com',
        tax_email: 'tax@perfumehouse108.com',
        tags: ['니치퍼퓸', '향수', '조향', '한국향수'],
        handle: 'perfumehouse108',
        instagram_handle: '@perfumehouse108',
        deposit_balance: 2000000,
    },
    {
        email: 'cs@hairlab.seoul',
        password: 'MockBrand2024!',
        display_name: '헤어랩 서울',
        bio: '시카/케라틴 특허 기술 헤어케어 브랜드. 살롱 퀄리티 홈케어 제품.',
        avatar_url: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=200&h=200&fit=crop',
        website: 'https://www.hairlab.seoul',
        business_category: '뷰티/헤어케어',
        business_type: '주식회사',
        business_number: '218-81-34567',
        representative_name: '김태형',
        company_address: '서울특별시 마포구 월드컵북로 60, 상암 IT센터 8F',
        company_phone: '02-6777-3300',
        contact_person_name: '변다은',
        contact_person_phone: '010-3300-5678',
        contact_person_email: 'daeun.byun@hairlab.seoul',
        tax_email: 'finance@hairlab.seoul',
        tags: ['헤어케어', '샴푸', '트리트먼트', '두피케어'],
        handle: 'hairlab_seoul',
        instagram_handle: '@hairlab_seoul',
        deposit_balance: 2500000,
    },
    {
        email: 'partner@nailstudio-n.com',
        password: 'MockBrand2024!',
        display_name: '네일스튜디오 N',
        bio: '국내 1호 젤네일 D2C 브랜드. 4주 지속 홈젤네일 키트 및 네일아트 케어 라인.',
        avatar_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=200&h=200&fit=crop',
        website: 'https://www.nailstudio-n.com',
        business_category: '뷰티/네일',
        business_type: '주식회사',
        business_number: '220-87-11234',
        representative_name: '신예진',
        company_address: '인천광역시 연수구 송도동 151, 테크노파크 G동',
        company_phone: '032-340-8800',
        contact_person_name: '임채린',
        contact_person_phone: '010-8800-3456',
        contact_person_email: 'chaerin.im@nailstudio-n.com',
        tax_email: 'billing@nailstudio-n.com',
        tags: ['네일', '젤네일', '홈네일', '네일케어'],
        handle: 'nailstudio_n',
        instagram_handle: '@nailstudio_n',
        deposit_balance: 1800000,
    },
    {
        email: 'info@sunscreenlab.kr',
        password: 'MockBrand2024!',
        display_name: '선스크린랩',
        bio: 'SPF50+ 전문 자외선 차단제 브랜드. 가볍고 투명한 선케어의 새로운 기준.',
        avatar_url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=200&h=200&fit=crop',
        website: 'https://www.sunscreenlab.kr',
        business_category: '뷰티/선케어',
        business_type: '유한회사',
        business_number: '124-87-23456',
        representative_name: '조현우',
        company_address: '서울특별시 송파구 올림픽로 300, 롯데월드타워 27F',
        company_phone: '02-2222-1111',
        contact_person_name: '강나연',
        contact_person_phone: '010-1111-5678',
        contact_person_email: 'nayeon.kang@sunscreenlab.kr',
        tax_email: 'tax@sunscreenlab.kr',
        tags: ['선크림', '자외선차단', '선케어', 'SPF'],
        handle: 'sunscreenlab_kr',
        instagram_handle: '@sunscreenlab_kr',
        deposit_balance: 2000000,
    },
    // ── 패션 (5)
    {
        email: 'brand@ateliermuji.kr',
        password: 'MockBrand2024!',
        display_name: '아뜰리에 무지',
        bio: '미니멀리즘 철학의 국내 패션 브랜드. 심플하지만 고급스러운 오피스/데일리웨어.',
        avatar_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop',
        website: 'https://www.ateliermuji.kr',
        business_category: '패션/의류',
        business_type: '주식회사',
        business_number: '106-81-78901',
        representative_name: '이승민',
        company_address: '서울특별시 강남구 도산대로 311, 청담패션빌딩 5F',
        company_phone: '02-540-7700',
        contact_person_name: '나은지',
        contact_person_phone: '010-7700-1234',
        contact_person_email: 'eunji.na@ateliermuji.kr',
        tax_email: 'account@ateliermuji.kr',
        tags: ['미니멀', '오피스룩', '여성패션', '데일리웨어'],
        handle: 'atelier_muji',
        instagram_handle: '@atelier_muji_kr',
        deposit_balance: 4500000,
    },
    {
        email: 'hello@vntagecollect.com',
        password: 'MockBrand2024!',
        display_name: '빈티지 컬렉트',
        bio: '엄선한 빈티지/리셀 아이템 큐레이션샵. Y2K·레트로 무드 한정판 컬렉션 전문.',
        avatar_url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=200&h=200&fit=crop',
        website: 'https://www.vntagecollect.com',
        business_category: '패션/빈티지',
        business_type: '개인사업자',
        business_number: '311-09-12345',
        representative_name: '최하린',
        company_address: '서울특별시 마포구 와우산로 48, 홍대입구 3F',
        company_phone: '02-333-5544',
        contact_person_name: '최하린',
        contact_person_phone: '010-5544-2233',
        contact_person_email: 'harin.choi@vntagecollect.com',
        tax_email: 'tax@vntagecollect.com',
        tags: ['빈티지', 'Y2K', '리셀', '스트릿패션'],
        handle: 'vntage_collect',
        instagram_handle: '@vntage_collect',
        deposit_balance: 1200000,
    },
    {
        email: 'cs@plussize.styleup.kr',
        password: 'MockBrand2024!',
        display_name: '사이즈업 스타일',
        bio: '44~66 전 사이즈를 패셔너블하게. 플러스사이즈 여성 전문 트렌디 패션 브랜드.',
        avatar_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=200&h=200&fit=crop',
        website: 'https://www.styleup.kr',
        business_category: '패션/플러스사이즈',
        business_type: '주식회사',
        business_number: '220-81-56789',
        representative_name: '황지영',
        company_address: '경기도 의정부시 청사로 64, 의정부라온빌딩 3F',
        company_phone: '031-870-4400',
        contact_person_name: '서민아',
        contact_person_phone: '010-4400-8899',
        contact_person_email: 'mina.seo@styleup.kr',
        tax_email: 'billing@styleup.kr',
        tags: ['플러스사이즈', '여성패션', '빅사이즈', '트렌디'],
        handle: 'size_up_style',
        instagram_handle: '@size_up_style',
        deposit_balance: 2500000,
    },
    {
        email: 'brand@denim8factory.kr',
        password: 'MockBrand2024!',
        display_name: '데님8 팩토리',
        bio: '남녀 데님 전문 캐쥬얼 브랜드. 청바지 핏 맞춤 서비스 + 지속가능 생산 지향.',
        avatar_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=200&h=200&fit=crop',
        website: 'https://www.denim8factory.kr',
        business_category: '패션/데님',
        business_type: '주식회사',
        business_number: '109-86-34512',
        representative_name: '박도유',
        company_address: '서울특별시 중구 을지로 158, 힙지로빌딩 7F',
        company_phone: '02-2266-8800',
        contact_person_name: '류수빈',
        contact_person_phone: '010-8800-6677',
        contact_person_email: 'subin.ryu@denim8factory.kr',
        tax_email: 'finance@denim8factory.kr',
        tags: ['데님', '청바지', '캐주얼', '남녀공용'],
        handle: 'denim8_factory',
        instagram_handle: '@denim8_factory',
        deposit_balance: 3000000,
    },
    {
        email: 'hello@knitwear.haneul.kr',
        password: 'MockBrand2024!',
        display_name: '하늘 니트웨어',
        bio: '제주 감성 담은 페미닌 니트 전문 브랜드. 핸드메이드 질감의 프리미엄 니트 라인업.',
        avatar_url: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=200&h=200&fit=crop',
        website: 'https://www.haneulknitwear.kr',
        business_category: '패션/니트웨어',
        business_type: '개인사업자',
        business_number: '616-34-78901',
        representative_name: '이하늘',
        company_address: '제주특별자치도 제주시 애월읍 구엄리 1456-3',
        company_phone: '064-712-3456',
        contact_person_name: '이하늘',
        contact_person_phone: '010-3456-7812',
        contact_person_email: 'haneul@knitwear.haneul.kr',
        tax_email: 'tax@knitwear.haneul.kr',
        tags: ['니트', '가디건', '페미닌', '핸드메이드'],
        handle: 'haneul_knitwear',
        instagram_handle: '@haneul_knitwear',
        deposit_balance: 1500000,
    },
    // ── 피트니스/헬스 (4)
    {
        email: 'cs@proteinbar.kr',
        password: 'MockBrand2024!',
        display_name: '프로틴바 코리아',
        bio: '단백질 함유량 30g+ 국내 1위 프로틴바 브랜드. 맛있는 건강 간식의 새로운 기준.',
        avatar_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=200&h=200&fit=crop',
        website: 'https://www.proteinbar.kr',
        business_category: '건강식품/단백질식품',
        business_type: '주식회사',
        business_number: '215-81-90123',
        representative_name: '강준호',
        company_address: '충청북도 청주시 흥덕구 옥산면 산단로 19, 식품공장',
        company_phone: '043-289-7000',
        contact_person_name: '정은채',
        contact_person_phone: '010-7000-2345',
        contact_person_email: 'eunchae.jeong@proteinbar.kr',
        tax_email: 'tax@proteinbar.kr',
        tags: ['단백질', '프로틴바', '헬스', '건강간식'],
        handle: 'proteinbar_korea',
        instagram_handle: '@proteinbar_korea',
        deposit_balance: 3500000,
    },
    {
        email: 'brand@athleisurelab.com',
        password: 'MockBrand2024!',
        display_name: '애슬레저랩',
        bio: '일상과 운동을 넘나드는 프리미엄 애슬레저 웨어 브랜드. 기능성 + 스타일 양립.',
        avatar_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=200&h=200&fit=crop',
        website: 'https://www.athleisurelab.com',
        business_category: '패션/스포츠웨어',
        business_type: '주식회사',
        business_number: '120-81-45678',
        representative_name: '유다인',
        company_address: '서울특별시 강동구 천호대로 1077, 스포츠콤플렉스 B동',
        company_phone: '02-480-9900',
        contact_person_name: '고보람',
        contact_person_phone: '010-9900-1122',
        contact_person_email: 'boram.ko@athleisurelab.com',
        tax_email: 'billing@athleisurelab.com',
        tags: ['애슬레저', '요가웨어', '운동복', '기능성'],
        handle: 'athleisure_lab',
        instagram_handle: '@athleisure_lab_kr',
        deposit_balance: 4000000,
    },
    {
        email: 'hello@cleanvitamin.kr',
        password: 'MockBrand2024!',
        display_name: '클린비타민',
        bio: '국내 GMP 인증 영양제 브랜드. 합성 첨가물 ZERO, 식약처 인증 클린 서플리먼트.',
        avatar_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&h=200&fit=crop',
        website: 'https://www.cleanvitamin.kr',
        business_category: '건강식품/영양제',
        business_type: '주식회사',
        business_number: '314-81-23456',
        representative_name: '문재원',
        company_address: '경기도 성남시 분당구 판교역로 166, 카카오판교아지트 5F',
        company_phone: '031-776-8800',
        contact_person_name: '백지수',
        contact_person_phone: '010-8800-3344',
        contact_person_email: 'jisoo.baek@cleanvitamin.kr',
        tax_email: 'account@cleanvitamin.kr',
        tags: ['영양제', '비타민', '이너뷰티', '클린뷰티'],
        handle: 'cleanvitamin_kr',
        instagram_handle: '@cleanvitamin_kr',
        deposit_balance: 3000000,
    },
    {
        email: 'brand@fitnessplanner.kr',
        password: 'MockBrand2024!',
        display_name: '핏플래너',
        bio: '스마트 홈트레이닝 기기 + AI 맞춤 운동 플랜 SaaS. 운동 초보도 쉬운 홈짐 솔루션.',
        avatar_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop',
        website: 'https://www.fitnessplanner.kr',
        business_category: '피트니스/헬스테크',
        business_type: '주식회사',
        business_number: '150-81-67890',
        representative_name: '홍태양',
        company_address: '서울특별시 서초구 강남대로 479, 신논현 IT빌딩 11F',
        company_phone: '02-3476-5500',
        contact_person_name: '김나은',
        contact_person_phone: '010-5500-7788',
        contact_person_email: 'naeun.kim@fitnessplanner.kr',
        tax_email: 'tax@fitnessplanner.kr',
        tags: ['홈트', '운동기기', '헬스테크', 'AI운동'],
        handle: 'fit_planner_kr',
        instagram_handle: '@fit_planner_kr',
        deposit_balance: 2500000,
    },
    // ── 라이프스타일/푸드/인테리어 (4)
    {
        email: 'hello@homecafe.brand.kr',
        password: 'MockBrand2024!',
        display_name: '리빙카페 홈',
        bio: '홈카페 전문 커피 원두·도구·소품 브랜드. 카페 감성을 집에서 재현하는 모든 것.',
        avatar_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=200&h=200&fit=crop',
        website: 'https://www.homecafebrand.kr',
        business_category: '라이프스타일/홈카페',
        business_type: '주식회사',
        business_number: '214-86-56789',
        representative_name: '서준혁',
        company_address: '서울특별시 중구 을지로 160, 리빙카페 본사',
        company_phone: '02-753-4400',
        contact_person_name: '조지민',
        contact_person_phone: '010-4400-5566',
        contact_person_email: 'jimin.cho@homecafebrand.kr',
        tax_email: 'finance@homecafebrand.kr',
        tags: ['홈카페', '커피', '드립', '캡슐커피'],
        handle: 'livingcafe_home',
        instagram_handle: '@livingcafe_home',
        deposit_balance: 2000000,
    },
    {
        email: 'brand@hanbokcouture.com',
        password: 'MockBrand2024!',
        display_name: '한복꾸뛰르',
        bio: '현대적으로 재해석한 생활한복 브랜드. 일상에서 입는 모던 한복 및 한복 소품.',
        avatar_url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=200&h=200&fit=crop',
        website: 'https://www.hanbokcouture.com',
        business_category: '패션/전통의상',
        business_type: '유한회사',
        business_number: '420-12-34567',
        representative_name: '김소이',
        company_address: '전라북도 전주시 완산구 태조로 44, 전주한옥마을 내',
        company_phone: '063-288-7788',
        contact_person_name: '김소이',
        contact_person_phone: '010-7788-3322',
        contact_person_email: 'soi@hanbokcouture.com',
        tax_email: 'tax@hanbokcouture.com',
        tags: ['한복', '생활한복', '전통', '한국문화'],
        handle: 'hanbok_couture',
        instagram_handle: '@hanbok_couture',
        deposit_balance: 1500000,
    },
    {
        email: 'cs@greenroom.interior.kr',
        password: 'MockBrand2024!',
        display_name: '그린룸 인테리어',
        bio: '식물+인테리어 라이프스타일 브랜드. 플랜테리어 소품·화분·드라이플라워 큐레이션.',
        avatar_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=200&h=200&fit=crop',
        website: 'https://www.greenroominterior.kr',
        business_category: '라이프스타일/인테리어',
        business_type: '주식회사',
        business_number: '125-87-89012',
        representative_name: '류예림',
        company_address: '서울특별시 성동구 왕십리로 115, 성수연방 3층',
        company_phone: '02-2285-7700',
        contact_person_name: '전수아',
        contact_person_phone: '010-7700-8899',
        contact_person_email: 'sua.jeon@greenroominterior.kr',
        tax_email: 'billing@greenroominterior.kr',
        tags: ['플랜테리어', '인테리어', '식물', '드라이플라워'],
        handle: 'greenroom_interior',
        instagram_handle: '@greenroom_interior',
        deposit_balance: 1800000,
    },
    {
        email: 'info@orgnatrue.jeju.kr',
        password: 'MockBrand2024!',
        display_name: '제주 오가나처',
        bio: '제주 유기농 원물 기반 친환경 식품·뷰티 브랜드. 제로웨이스트 패키징 지향.',
        avatar_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=200&h=200&fit=crop',
        website: 'https://www.orgnatrue.jeju.kr',
        business_category: '라이프스타일/친환경',
        business_type: '주식회사',
        business_number: '616-81-23457',
        representative_name: '고예린',
        company_address: '제주특별자치도 서귀포시 안덕면 화순로 67, 제주농업협동조합 내',
        company_phone: '064-794-8800',
        contact_person_name: '고예린',
        contact_person_phone: '010-2233-8800',
        contact_person_email: 'yerim@orgnatrue.jeju.kr',
        tax_email: 'eco@orgnatrue.jeju.kr',
        tags: ['제주', '친환경', '오가닉', '제로웨이스트'],
        handle: 'orgnatrue_jeju',
        instagram_handle: '@orgnatrue_jeju',
        deposit_balance: 1200000,
    },
]

async function main() {
    console.log('🏢 20개 브랜드 계정 시딩 시작...\n')

    // 기존 mock 브랜드 삭제 처리
    const emails = BRANDS.map(b => b.email)
    let page = 0
    const PAGE_SIZE = 50
    while (true) {
        const { data: existingUsers } = await supabase.auth.admin.listUsers({ page, perPage: PAGE_SIZE })
        if (!existingUsers || existingUsers.users.length === 0) break
        for (const u of existingUsers.users) {
            if (emails.includes(u.email || '')) {
                await supabase.auth.admin.deleteUser(u.id)
                console.log(`  🗑️  기존 삭제: ${u.email}`)
            }
        }
        if (existingUsers.users.length < PAGE_SIZE) break
        page++
    }

    let successCount = 0

    for (const brand of BRANDS) {
        try {
            // 1. Auth 계정 생성
            const { data: authData, error: authErr } = await supabase.auth.admin.createUser({
                email: brand.email,
                password: brand.password,
                email_confirm: true,
                user_metadata: { role: 'brand', is_mock: true },
            })
            if (authErr || !authData?.user) {
                console.error(`  ❌ Auth 생성 실패 (${brand.email}):`, authErr?.message)
                continue
            }
            const userId = authData.user.id

            // 2. profiles 삽입
            const profilePayload = {
                id: userId,
                email: brand.email,
                role: 'brand',
                display_name: brand.display_name,
                bio: brand.bio,
                avatar_url: brand.avatar_url,
                website: brand.website,
                handle: brand.handle,
                instagram_handle: brand.instagram_handle,
                is_mock: true,
                business_category: brand.business_category,
                business_type: brand.business_type,
                business_number: brand.business_number,
                representative_name: brand.representative_name,
                company_address: brand.company_address,
                company_phone: brand.company_phone,
                contact_person_name: brand.contact_person_name,
                contact_person_phone: brand.contact_person_phone,
                contact_person_email: brand.contact_person_email,
                tax_email: brand.tax_email,
                tags: brand.tags,
                deposit_balance: brand.deposit_balance,
                primary_region: '서울',
            }

            const { error: profErr } = await supabase
                .from('profiles')
                .upsert(profilePayload, { onConflict: 'id' })

            if (profErr) {
                console.error(`  ❌ profiles 삽입 실패 (${brand.display_name}):`, profErr.message)
                await supabase.auth.admin.deleteUser(userId)
                continue
            }

            console.log(`  ✅ ${brand.display_name.padEnd(20)} | ${brand.business_category} | 예치금 ${brand.deposit_balance.toLocaleString()}원`)
            successCount++
        } catch (err: any) {
            console.error(`  💥 예외 발생 (${brand.email}):`, err.message)
        }
    }

    console.log(`\n🎉 총 ${successCount}/${BRANDS.length}개 브랜드 계정 생성 완료!`)
    console.log('\n📧 브랜드 계정 로그인 정보:')
    console.log('   비밀번호: MockBrand2024! (전 계정 동일)')
    BRANDS.forEach(b => console.log(`   - ${b.email}`))
}

main().catch(console.error)
